version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn audiophile.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
